autosave_form: 1.2.0
bg_image_formatter: 1.14.0
blazy: 2.2.0
block: 8.9.16
block_content: 8.9.16
bootstrap_layout_builder: 2.0.1
bootstrap_layouts: 5.2.0
bootstrap_styles: 1.0.3
breakpoint: 8.9.16
ckeditor: 8.9.16
config: 8.9.16
conflict: 2.0.0-alpha2
consumers: 1.11.0
contact: 8.9.16
contact_storage: 1.1.0
content_moderation: 8.9.16
contextual: 8.9.16
crop: 2.1.0
ctools: 3.6.0
datetime: 8.9.16
dblog: 8.9.16
devel: 2.1.0
diff: 1.0.0
dropzonejs: 2.5.0
editor: 8.9.16
entity_block: 1.0.0-beta3
entity_browser: 2.5.0
entity_browser_block: 1.1.0
field: 8.9.16
field_ui: 8.9.16
file: 8.9.16
filter: 8.9.16
help: 8.9.16
history: 8.9.16
image: 8.9.16
image_widget_crop: 2.3.0
inline_entity_form: 1.0.0-rc9
jsonapi: 0.0.0
layout_builder: 8.9.16
layout_builder_restrictions: 2.8.0
layout_builder_styles: 1.0.0-beta4
layout_discovery: 8.9.16
layout_library: 1.0.0-beta2
lightning: 4.0.5
lightning_api: 4.6.0
lightning_banner_block: 2.10.0
lightning_contact_form: 5.6.0
lightning_core: 5.6.0
lightning_landing_page: 2.10.0
lightning_layout: 2.10.0
lightning_map_block: 2.10.0
lightning_media: 4.6.0
lightning_media_audio: 4.6.0
lightning_media_bulk_upload: 4.6.0
lightning_media_document: 4.6.0
lightning_media_image: 4.6.0
lightning_media_instagram: 4.6.0
lightning_media_slideshow: 4.6.0
lightning_media_twitter: 4.6.0
lightning_media_video: 4.6.0
lightning_page: 5.6.0
lightning_roles: 5.6.0
lightning_scheduler: 3.16.0
lightning_search: 5.6.0
lightning_workflow: 3.16.0
link: 8.9.16
media: 8.9.16
media_entity_instagram: 3.0.5
media_entity_twitter: 2.7.0
media_library: 8.9.16
media_library_form_element: 2.0.3
media_library_theme_reset: 1.1.0
menu_link_content: 8.9.16
menu_ui: 8.9.16
metatag: 1.16.0
moderation_dashboard: 1.0.0-beta2
moderation_sidebar: 1.4.0
node: 8.9.16
openapi: 2.0.0-rc3
openapi_jsonapi: 2.0.0
openapi_ui: 1.0.0-rc3
openapi_ui_redoc: 1.0.0-rc3
openapi_ui_swagger: 1.0.0-rc4
options: 8.9.16
page_cache: 8.9.16
page_manager: 4.0.0-beta6
panels: 4.6.0
path: 8.9.16
path_alias: 8.9.16
pathauto: 1.8.0
quickedit: 8.9.16
rdf: 8.9.16
redirect: 1.6.0
schemata: 1.0.0-beta2
schemata_json_schema: 1.0.0-beta2
search_api: 1.19.0
search_api_db: 1.19.0
seckit: 1.2.0
serialization: 8.9.16
shortcut: 8.9.16
simple_gmap: 3.0.1
simple_oauth: 4.5.0
slick: 2.3.0
slick_entityreference: 2.0.0
system: 8.9.16
taxonomy: 8.9.16
text: 8.9.16
token: 1.9.0
toolbar: 8.9.16
user: 8.9.16
views: 8.9.16
views_ui: 8.9.16
workflows: 8.9.16
